version: 2

project_name: gitr

before:
  hooks:
    - go mod tidy

builds:
  - id: gitr
    main: .
    binary: gitr
    ldflags:
      - -s -w -X github.com/swarupdonepudi/gitr/cmd/gitr/root.VersionLabel={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

release:
  github:
    owner: swarupdonepudi
    name: gitr

homebrew_casks:
  - name: gitr
    repository:
      owner: swarupdonepudi
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/swarupdonepudi/gitr
    description: "gitr: git rapid - save time by opening git repos on web right from the command line"
    binaries:
      - gitr
    postflight: |
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitr"]
    caveats: |
      Installation Complete!

      gitr helps you open git repositories in your browser instantly.

      Quick Start

      1. Navigate to any git repository:
         cd ~/your-project

      2. Open the repo in your browser:
         gitr

      3. Open a specific page:
         gitr pulls     # Pull requests
         gitr issues    # Issues
         gitr actions   # GitHub Actions

      4. Clone any repo with a short URL:
         gitr clone gh/owner/repo

      For more commands, run:
         gitr --help

      Documentation: https://gitr.dev
